version: '3.8'

services:
  backend-api-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /security/:/security/:ro
    environment:
      - BACKEND_ACCOUNT_KEY


  web-prod:
    depends_on:
      - backend-api-prod
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_REACT_APP_API_URL
    ports:
      - 3000:3000
    stdin_open: true 
    restart: always
    volumes:
      - ./web/configs/:/etc/nginx/conf.d/:ro
      - /web/node_modules 
