version: '2'
services:
  config-server:
    container_name: smartbeehive
    build:
      context: backend/
      dockerfile: Dockerfile
    image: smartbeehive:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge